[package]
name = "eth-rlp-verify"
version = "0.1.0"
edition = "2021"

[dependencies]
rlp = "0.6.1"
ethereum-types = "0.15.1"
sha3 = "0.10"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
dotenv = "0.15"

# Optional: Remove if async support is no longer required.
tokio = { version = "1.40", features = ["full"] }

[lib]
name = "eth_rlp_verify"
path = "src/lib.rs"

# Optional dependencies that you might want to remove if you don't need them
# anymore, especially `reqwest` and `clap`, since you're removing the binary.
[dependencies.reqwest]
version = "0.12.7"
features = ["json"]

[dependencies.clap]
version = "4.5"
features = ["derive"]
