name: Rust CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta, nightly]
        include:
          - rust: stable
            features: ""
          - rust: nightly
            features: "unstable"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install Dependencies
        run: |
          rustup component add clippy rustfmt

      - name: Build the project
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --all-features

      - name: Run Clippy (linter)
        run: cargo clippy --all-features -- -D warnings

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/debug/deps/*.d

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/debug/incremental
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.rust }}-
